print("Hello from lesson 1")

######### The below is the code required for task 2a ##########
# print("1")
# print("2")
# print("3")
# print("4")
# print("5")
# print("6")
# print("7")
# print("8")
print("9")
# print("10")
# print("11")
# print("12")
# print("13")
# print("14")
# print("15")
# print("16")
# print("17")
# print("18")
# print("19")
# print("20")
# print("21")
# print("22")
# print("23")
# print("24")
# print("25")
# print("26")
# print("27")
# print("28")
# print("29")
# print("30")
# print("31")

# print("January")
# print("February")
# print("March")
# print("April")
# print("May")
# print("June")
# print("July")
# print("August")
# print("September")
print("October")
# print("November")
# print("December")

# print("2020")
# print("2021")
# print("2022")
# print("2023")
# print("2024")
print ("2025")
# print("2026")
# print("2027")
# print("2028")
# print("2029")
# print("2030")

############## Below is the code for task 2b ##############
# print("1")
# print("2")
# print("3")
# print("4")
# print("5")
# print("6")
# print("7")
# print("8")
print("9")
# print("10")
# print("11")
# print("12")
# print("13")
# print("14")
# print("15")
# print("16")
# print("17")
# print("18")
# print("19")
# print("20")
# print("21")
# print("22")
# print("23")
# print("24")
# print("25")
# print("26")
# print("27")
# print("28")
# print("29")
# print("30")
# print("31")

# print("January")
# print("February")
# print("March")
# print("April")
# print("May")
# print("June")
# print("July")
# print("August")
# print("September")
print("October")
# print("November")
# print("December")

# print("2020")
# print("2021")
# print("2022")
# print("2023")
# print("2024")
print("2025")
# print("2026")
# print("2027")
# print("2028")
# print("2029")
# print("2030")
print("i have $10")
print("twenty-twelve")
print("My favourite food is udon")
print("my name is tytus")
print ("my age is 12")
print("my school is mayflower")
print ("i want robux")
print("wake up")
print("go toilet")
print("shower")
print("dress up")
print("go to school")
print("Hello and how are you?")

print("What is wrong with this")

print("Why is this not working?")

print("Why is this not working?")